import localFont from "next/font/local";
import "./globals.css";
import { Metadata } from "next";
const sharpFont = localFont({
  variable: "--font-sharp",
  src: [
    { path: "../fonts/SharpGrotesk-Book20.otf", weight: "400" },
    { path: "../fonts/SharpGrotesk-Medium20.otf", weight: "500" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sharpFont.className}`}>
      <main className="w-full h-full" id="main-container">
        <body>{children}</body>
      </main>
    </html>
  );
}
